<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="H.NotifyIcon.Wpf" />
    <PackageReference Include="Microsoft.Toolkit.Uwp.Notifications" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FreeSpaceWatcher.Core\FreeSpaceWatcher.Core.csproj" />
  </ItemGroup>
</Project>
